# Generated by Django 5.1.7 on 2025-03-31 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_logbook_driver_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogEntry',
            new_name='LogBookEntry',
        ),
    ]
