# Generated by Django 5.2 on 2025-05-06 08:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_number', models.CharField(db_index=True, max_length=7)),
                ('driver_initials', models.CharField(max_length=2)),
                ('co_driver_name', models.CharField(blank=True, max_length=250, null=True)),
                ('home_operating_center_address', models.CharField(max_length=250)),
                ('vehicle_number', models.CharField(max_length=5)),
                ('show_each_unit', models.CharField(max_length=8)),
                ('other_trailers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('shipper', models.CharField(max_length=250)),
                ('commodity', models.CharField(max_length=250)),
                ('load_no', models.CharField(max_length=12)),
                ('other_loads', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('today_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty (Not Driving)')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=250)),
                ('odometer_start', models.PositiveIntegerField()),
                ('odometer_end', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField()),
                ('log_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='core.logbook')),
            ],
        ),
    ]
