# Generated by Django 5.2 on 2025-04-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='driver_signature',
        ),
    ]
