# Generated by Django 5.1.7 on 2025-03-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='driver_signature',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
