# Generated by Django 5.2 on 2025-04-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_logbook_driver_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbookentry',
            name='logbook',
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='log_book',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='core.logbook'),
            preserve_default=False,
        ),
    ]
