# Generated by Django 5.1.7 on 2025-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_logentry_logbookentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
